function Hd = nyqst2
%NYQST2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 18-Mar-2014 00:32:53

B     = 2;    % Number of Bands
TW    = 0.1;  % Transition Width
Astop = 80;   % Stopband Attenuation (dB)

h = fdesign.nyquist(B, 'tw,ast', TW, Astop);

Hd = design(h, 'kaiserwin');



